## datasummary_df {.unnumbered}


Draw a table from a data.frame

### Description

Draw a table from a data.frame



### Usage

<pre><code class='language-R'>datasummary_df(
  data,
  output = "default",
  fmt = 2,
  align = NULL,
  hrule = NULL,
  title = NULL,
  notes = NULL,
  add_rows = NULL,
  add_columns = NULL,
  escape = TRUE,
  ...
)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="datasummary_df_:_data">data</code></td>
<td>
A data.frame (or tibble)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="datasummary_df_:_output">output</code></td>
<td>
filename or object type (character string)


<ul>
<li> Supported filename extensions: .docx, .html, .tex, .md, .txt, .csv, .xlsx, .png, .jpg

</li>
<li> Supported object types: &quot;default&quot;, &quot;html&quot;, &quot;markdown&quot;, &quot;latex&quot;, &quot;latex_tabular&quot;, &quot;data.frame&quot;, &quot;gt&quot;, &quot;kableExtra&quot;, &quot;huxtable&quot;, &quot;flextable&quot;, &quot;DT&quot;, &quot;jupyter&quot;. The &quot;modelsummary_list&quot; value produces a lightweight object which can be saved and fed back to the <code>modelsummary</code> function.

</li>
<li> The &quot;default&quot; output format can be set to &quot;kableExtra&quot;, &quot;gt&quot;, &quot;flextable&quot;, &quot;huxtable&quot;, &quot;DT&quot;, or &quot;markdown&quot;


<ul>
<li> If the user does not choose a default value, the packages listed above are tried in sequence.

</li>
<li> Session-specific configuration: <code>options("modelsummary_factory_default" = "gt")</code>

</li>
<li> Persistent configuration: <code>config_modelsummary(output = "markdown")</code>

</li></ul>

</li>
<li> Warning: Users should not supply a file name to the <code>output</code> argument if they intend to customize the table with external packages. See the 'Details' section.

</li>
<li> LaTeX compilation requires the <code>booktabs</code> and <code>siunitx</code> packages, but <code>siunitx</code> can be disabled or replaced with global options. See the 'Details' section.

</li></ul>
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="datasummary_df_:_fmt">fmt</code></td>
<td>
how to format numeric values: integer, user-supplied function, or <code>modelsummary</code> function.


<ul>
<li> Integer: Number of decimal digits

</li>
<li> User-supplied functions:


<ul>
<li> Any function which accepts a numeric vector and returns a character vector of the same length.

</li></ul>

</li>
<li> <code>modelsummary</code> functions:


<ul>
<li> <code>fmt = fmt_significant(2)</code>: Two significant digits (at the term-level)

</li>
<li> <code>fmt = fmt_sprintf("%.3f")</code>: See <code>?sprintf</code>

</li>
<li> <code>fmt = fmt_identity()</code>: unformatted raw values

</li></ul>

</li></ul>
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="datasummary_df_:_align">align</code></td>
<td>
A string with a number of characters equal to the number of columns in
the table (e.g., <code>align = "lcc"</code>).  Valid characters: l, c, r, d.


<ul>
<li> &quot;l&quot;: left-aligned column

</li>
<li> &quot;c&quot;: centered column

</li>
<li> &quot;r&quot;: right-aligned column

</li>
<li> &quot;d&quot;: dot-aligned column. For LaTeX/PDF output, this option requires at least version 3.0.25 of the siunitx LaTeX package. These commands must appear in the LaTeX preamble (they are added automatically when compiling Rmarkdown documents to PDF):


<ul>
<li> `\usepackage{booktabs}`

</li>
<li> `\usepackage{siunitx}`

</li>
<li> `\newcolumntype{d}{S[ input-open-uncertainty=, input-close-uncertainty=, parse-numbers = false, table-align-text-pre=false, table-align-text-post=false ]}`

</li></ul>

</li></ul>
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="datasummary_df_:_hrule">hrule</code></td>
<td>
position of horizontal rules (integer vector)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="datasummary_df_:_title">title</code></td>
<td>
string
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="datasummary_df_:_notes">notes</code></td>
<td>
list or vector of notes to append to the bottom of the table.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="datasummary_df_:_add_rows">add_rows</code></td>
<td>
a data.frame (or tibble) with the same number of columns as
your main table. By default, rows are appended to the bottom of the table.
You can define a &quot;position&quot; attribute of integers to set the row positions.
See Examples section below.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="datasummary_df_:_add_columns">add_columns</code></td>
<td>
a data.frame (or tibble) with the same number of rows as
your main table.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="datasummary_df_:_escape">escape</code></td>
<td>
boolean TRUE escapes or substitutes LaTeX/HTML characters which could
prevent the file from compiling/displaying. This setting does not affect captions or notes.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="datasummary_df_:_...">...</code></td>
<td>
all other arguments are passed through to the table-making
functions kableExtra::kbl, gt::gt, DT::datatable, etc. depending on the <code>output</code> argument.
This allows users to pass arguments directly to <code>datasummary</code> in order to
affect the behavior of other functions behind the scenes.
</td></tr>
</table>


### References

Arel-Bundock V (2022). “modelsummary: Data and Model Summaries in R.” <em>Journal of Statistical Software</em>, <em>103</em>(1), 1-23. \Sexpr[results=rd]{tools:::Rd_expr_doi("10.18637/jss.v103.i01")}.'

