# Themes & Styles 

```{r, include = FALSE}
options(modelsummary_factory_default = "gt")
```

To customize the appearance of tables, `modelsummary` supports five of the most popular table-making packages: 

1. [`gt`: https://gt.rstudio.com](https://gt.rstudio.com)
2. [`kableExtra`: http://haozhu233.github.io/kableExtra](http://haozhu233.github.io/kableExtra)
3. [`huxtable`: https://hughjonesd.github.io/huxtable/](https://hughjonesd.github.io/huxtable/)
4. [`flextable`: https://davidgohel.github.io/flextable/](https://davidgohel.github.io/flextable/)
5. [`DT`: https://rstudio.github.io/DT](https://rstudio.github.io/DT)

Users are encouraged to visit these websites to determine which package suits their needs best. Each of them has different strengths and weaknesses. For instance, `gt` allows seamless integration with the RStudio IDE, but `kableExtra`'s LaTeX (and PDF) output is far more mature.

To create customized tables, the analyst begins by calling `modelsummary(models)` to create a summary table. Then, she *post-processes* the table by applying functions from one of the packages listed above. It is often convenient to use the `%>%` operator to do this.

To illustrate, we download data from the [Rdatasets repository](https://vincentarelbundock.github.io/Rdatasets') and we estimate 5 models: