---
title: "Multiple imputation"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

`modelsummary` can pool and display analyses on several datasets imputed using the `mice` or `Amelia` packages. In this example, we use convenience functions from the `mitools` package to format our data: 

```{r}
library(modelsummary)
library(mitools)
suppressMessages(library(mice))
suppressMessages(library(Amelia))

# Download data from `Rdatasets`
url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url)[, c('Clergy', 'Commerce', 'Literacy')]

# Insert missing values
dat$Clergy[sample(1:nrow(dat), 10)] <- NA
dat$Commerce[sample(1:nrow(dat), 10)] <- NA
dat$Literacy[sample(1:nrow(dat), 10)] <- NA

# Impute with `mice` and `Amelia`
dat_mice <- mice(dat, m = 5, printFlag = FALSE)
dat_amelia <- amelia(dat, m = 5, p2s = 0)
dat_amelia <- imputationList(dat_amelia$imputations)

# Estimate models
mod <- list()
mod[['Listwise deletion']] <- lm(Clergy ~ Literacy + Commerce, dat)
mod[['Mice']] <- with(dat_mice, lm(Clergy ~ Literacy + Commerce))
mod[['Amelia']] <- MIcombine(with(dat_amelia, lm(Clergy ~ Literacy + Commerce)))

# Summarize
msummary(mod)
```
